"""Shared Set E status vocabulary. Modules should use these values, not invent strings."""

from enum import StrEnum


class IntelligenceStatus(StrEnum):
    MAJOR_UPDATE = "MAJOR_UPDATE"
    MINOR_UPDATE = "MINOR_UPDATE"
    UPDATE = "UPDATE"
    NO_MAJOR_UPDATE = "NO_MAJOR_UPDATE"
    NO_RELEVANT_CONTENT = "NO_RELEVANT_CONTENT"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    BUDGET_SKIPPED = "BUDGET_SKIPPED"
    TRANSCRIPT_UNAVAILABLE = "TRANSCRIPT_UNAVAILABLE"
    ERROR = "ERROR"
    SOURCE_FAILURE = "SOURCE_FAILURE"
    RETRIEVAL_FAILURE = "RETRIEVAL_FAILURE"
    ANALYSIS_FAILURE = "ANALYSIS_FAILURE"


class ValidationStatus(StrEnum):
    VALID = "VALID"
    INVALID = "INVALID"


class PublicationStatus(StrEnum):
    PREPARED = "PREPARED"
    RENDERED = "RENDERED"
    DELIVERY_ATTEMPTED = "DELIVERY_ATTEMPTED"
    DELIVERY_CONFIRMED = "DELIVERY_CONFIRMED"
    DELIVERY_UNKNOWN = "DELIVERY_UNKNOWN"
    DELIVERY_FAILED = "DELIVERY_FAILED"
    ARCHIVE_ATTEMPTED = "ARCHIVE_ATTEMPTED"
    ARCHIVED = "ARCHIVED"
    RUN_COMPLETED = "RUN_COMPLETED"


class DeliveryStatus(StrEnum):
    DELIVERY_ATTEMPTED = "DELIVERY_ATTEMPTED"
    DELIVERY_CONFIRMED = "DELIVERY_CONFIRMED"
    DELIVERY_UNKNOWN = "DELIVERY_UNKNOWN"
    DELIVERY_FAILED = "DELIVERY_FAILED"


class PipelineStage(StrEnum):
    RUN_CREATED = "RUN_CREATED"
    CONFIG_RESOLVED = "CONFIG_RESOLVED"
    SOURCES_COLLECTING = "SOURCES_COLLECTING"
    NORMALIZED = "NORMALIZED"
    CLASSIFIED = "CLASSIFIED"
    MICRO_TOPIC_JOBS = "MICRO_TOPIC_JOBS"
    SYNTHESIS = "SYNTHESIS"
    NEWSLETTER_RENDERED = "NEWSLETTER_RENDERED"
    EMAIL_SENT = "EMAIL_SENT"
    ARCHIVED = "ARCHIVED"
    RUN_COMPLETED = "RUN_COMPLETED"
