"""Shared Set E status vocabulary. Modules should use these values, not invent strings."""

from enum import StrEnum


class IntelligenceStatus(StrEnum):
    MAJOR_UPDATE = "MAJOR_UPDATE"
    MINOR_UPDATE = "MINOR_UPDATE"
    UPDATE = "UPDATE"
    NO_MAJOR_UPDATE = "NO_MAJOR_UPDATE"
    NO_RELEVANT_CONTENT = "NO_RELEVANT_CONTENT"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    BUDGET_SKIPPED = "BUDGET_SKIPPED"
    TRANSCRIPT_UNAVAILABLE = "TRANSCRIPT_UNAVAILABLE"
    ERROR = "ERROR"
    SOURCE_FAILURE = "SOURCE_FAILURE"
    RETRIEVAL_FAILURE = "RETRIEVAL_FAILURE"
    ANALYSIS_FAILURE = "ANALYSIS_FAILURE"


class ValidationStatus(StrEnum):
    VALID = "VALID"
    INVALID = "INVALID"


class PublicationStatus(StrEnum):
    PREPARED = "PREPARED"
    RENDERED = "RENDERED"
    DELIVERY_ATTEMPTED = "DELIVERY_ATTEMPTED"
    DELIVERY_CONFIRMED = "DELIVERY_CONFIRMED"
    DELIVERY_UNKNOWN = "DELIVERY_UNKNOWN"
    DELIVERY_FAILED = "DELIVERY_FAILED"
    ARCHIVE_ATTEMPTED = "ARCHIVE_ATTEMPTED"
    ARCHIVED = "ARCHIVED"
    RUN_COMPLETED = "RUN_COMPLETED"


class DeliveryStatus(StrEnum):
    SKIPPED_DRY_RUN = "SKIPPED_DRY_RUN"
    DISABLED = "DISABLED"
    QUALITY_REVIEW_REQUIRED = "QUALITY_REVIEW_REQUIRED"
    DELIVERY_ATTEMPTED = "DELIVERY_ATTEMPTED"
    DELIVERY_CONFIRMED = "DELIVERY_CONFIRMED"
    DELIVERY_UNKNOWN = "DELIVERY_UNKNOWN"
    DELIVERY_FAILED = "DELIVERY_FAILED"


class SourceStatus(StrEnum):
    HEALTHY = "HEALTHY"
    EMPTY = "EMPTY"
    FAILED = "FAILED"
    DISABLED = "DISABLED"
    SOURCE_UNAVAILABLE = "SOURCE_UNAVAILABLE"


class PipelineStage(StrEnum):
    RUN_CREATED = "RUN_CREATED"
    CONFIG_RESOLVED = "CONFIG_RESOLVED"
    SOURCES_COLLECTING = "SOURCES_COLLECTING"
    NORMALIZED = "NORMALIZED"
    CLASSIFIED = "CLASSIFIED"
    MICRO_TOPIC_JOBS = "MICRO_TOPIC_JOBS"
    SYNTHESIS = "SYNTHESIS"
    NEWSLETTER_RENDERED = "NEWSLETTER_RENDERED"
    EMAIL_SENT = "EMAIL_SENT"
    ARCHIVED = "ARCHIVED"
    RUN_COMPLETED = "RUN_COMPLETED"

    # Canonical Set E stage names. Existing lifecycle names above remain for
    # compatibility; this vocabulary formalizes the full ordering contract.
    COLLECT = "COLLECT"
    CHEAP_FILTER = "CHEAP_FILTER"
    DEDUPLICATE = "DEDUPLICATE"
    ENTITY_EVENT = "ENTITY_EVENT"
    EVENT_GROUPING = "EVENT_GROUPING"
    THEME_ROUTING = "THEME_ROUTING"
    MICRO_TOPIC = "MICRO_TOPIC"
    RAG = "RAG"
    CONTEXT = "CONTEXT"
    AI = "AI"
    SCHEMA_VALIDATION = "SCHEMA_VALIDATION"
    SEMANTIC_VALIDATION = "SEMANTIC_VALIDATION"
    PROVENANCE = "PROVENANCE"
    BUSINESS_RULES = "BUSINESS_RULES"
    ENRICHMENT = "ENRICHMENT"
    NEWSLETTER = "NEWSLETTER"
    RENDER = "RENDER"
    SMTP = "SMTP"
    ARCHIVE = "ARCHIVE"


CANONICAL_PIPELINE_ORDER: tuple[PipelineStage, ...] = (
    PipelineStage.COLLECT,
    PipelineStage.NORMALIZED,
    PipelineStage.CHEAP_FILTER,
    PipelineStage.DEDUPLICATE,
    PipelineStage.CLASSIFIED,
    PipelineStage.ENTITY_EVENT,
    PipelineStage.EVENT_GROUPING,
    PipelineStage.THEME_ROUTING,
    PipelineStage.MICRO_TOPIC,
    PipelineStage.RAG,
    PipelineStage.CONTEXT,
    PipelineStage.AI,
    PipelineStage.SCHEMA_VALIDATION,
    PipelineStage.SEMANTIC_VALIDATION,
    PipelineStage.PROVENANCE,
    PipelineStage.BUSINESS_RULES,
    PipelineStage.ENRICHMENT,
    PipelineStage.SYNTHESIS,
    PipelineStage.NEWSLETTER,
    PipelineStage.RENDER,
    PipelineStage.SMTP,
    PipelineStage.ARCHIVE,
    PipelineStage.RUN_COMPLETED,
)
